Repository votingworks/vxsuite, pull requests merged in 2022-07, with the labels that each got.

#2079 restyle + refactor auth modals
  frontends/bsd/public/assets/remove-card.svg
  frontends/bsd/src/app.test.tsx
  frontends/bsd/src/app_root.tsx
  frontends/bsd/src/screens/invalid_card_screen.tsx
  frontends/election-manager/public/assets/remove-card.svg
  frontends/election-manager/src/app.test.tsx
  frontends/election-manager/src/components/election_manager.tsx
  frontends/election-manager/src/config/globals.ts
  frontends/election-manager/src/screens/invalid_card_screen.tsx
  frontends/election-manager/src/screens/smartcards_screen.tsx
  frontends/election-manager/src/screens/unlock_machine_screen.test.tsx
  frontends/election-manager/src/screens/unlock_machine_screen.tsx
  frontends/precinct-scanner/jest.config.js
  frontends/precinct-scanner/src/app_root.tsx
  frontends/precinct-scanner/src/preview_app.tsx
  frontends/precinct-scanner/src/screens/unlock_admin_screen.test.tsx
  frontends/precinct-scanner/src/screens/unlock_admin_screen.tsx
  libs/ui/src/__snapshots__/remove_card_page.test.tsx.snap
  libs/ui/src/globals.ts
  libs/ui/src/index.ts
  libs/ui/src/invalid_card_screen.test.tsx
  libs/ui/src/invalid_card_screen.tsx
  libs/ui/src/remove_card_page.test.tsx
  libs/ui/src/remove_card_page.tsx
  libs/ui/src/remove_card_screen.test.tsx
  libs/ui/src/remove_card_screen.tsx
  libs/ui/src/unlock_machine_screen.test.tsx
  libs/ui/src/unlock_machine_screen.tsx
Labels: user_facing_change

#2084 Make unconfigured machine screen default state of super admin Definition tab
  frontends/election-manager/src/app.test.tsx
  frontends/election-manager/src/app_root.tsx
  frontends/election-manager/src/components/election_manager.tsx
  frontends/election-manager/src/screens/unconfigured_screen.tsx
Labels: user_facing_change

#2090 (fix: precinct-scanner): Show warning when machine needs backup before being unconfigured
  frontends/precinct-scanner/src/api/scan.ts
  frontends/precinct-scanner/src/app.test.tsx
  frontends/precinct-scanner/src/app_root.tsx
  frontends/precinct-scanner/src/app_unhappy_paths.test.tsx
  frontends/precinct-scanner/src/screens/admin_screen.test.tsx
  frontends/precinct-scanner/src/screens/admin_screen.tsx
Labels: user_facing_change

#2098 fix(nh): correct orientation of scanned ballots
  libs/ballot-interpreter-nh/src/cli/interpret/index.ts
  libs/ballot-interpreter-nh/src/interpret/index.ts
  services/scan/src/util/save_images.ts
  services/scan/src/workers/interpret_nh.test.ts
  services/scan/src/workers/interpret_nh.ts
  services/scan/src/workers/interpret_vx.ts
Labels: user_facing_change

#2102 fix(scan): show overvote/blank sheet as overvote
  frontends/precinct-scanner/src/api/scan.ts
  frontends/precinct-scanner/src/app.test.tsx
  frontends/precinct-scanner/src/utils/build_scanning_result.test.ts
  frontends/precinct-scanner/src/utils/build_scanning_result.ts
Labels: user_facing_change

#2109 fix(nh): show contest title and adjudication ID
  frontends/election-manager/src/screens/write_ins_transcription_screen.tsx
Labels: user_facing_change

#2100 Consolidate new smartcards screens and tweak design
  frontends/election-manager/src/app.test.tsx
  frontends/election-manager/src/components/election_manager.tsx
  frontends/election-manager/src/config/types.ts
  frontends/election-manager/src/router_paths.ts
  frontends/election-manager/src/screens/election_smartcards_screen.tsx
  frontends/election-manager/src/screens/legacy_smartcards_screen.tsx
  frontends/election-manager/src/screens/smartcards_screen.tsx
  frontends/election-manager/src/screens/super_admin_smartcards_screen.tsx
Labels: user_facing_change

#2080 Split Reports & Tally screen
  frontends/election-manager/src/__snapshots__/app.test.tsx.snap
  frontends/election-manager/src/app.test.tsx
  frontends/election-manager/src/components/ballot_counts_table.test.tsx
  frontends/election-manager/src/components/ballot_counts_table.tsx
  frontends/election-manager/src/components/election_manager.tsx
  frontends/election-manager/src/components/navigation_screen.tsx
  frontends/election-manager/src/router_paths.ts
  frontends/election-manager/src/screens/ballot_list_screen.tsx
  frontends/election-manager/src/screens/printed_ballots_report_screen.tsx
  frontends/election-manager/src/screens/reports_screen.tsx
  frontends/election-manager/src/screens/tally_report_screen.tsx
  frontends/election-manager/src/screens/tally_screen.tsx
  frontends/election-manager/src/screens/write_ins_screen.tsx
  frontends/election-manager/src/utils/cast_vote_record_files.ts
  integration-testing/election-manager/cypress/integration/candidate_contest_tallies.ts
  integration-testing/election-manager/cypress/integration/tallies.ts
  integration-testing/election-manager/cypress/integration/yes_no_contest_tallies.ts
Labels: user_facing_change

#2125 Auto-open smartcard modal in relevant state when card is inserted and user is auth'd as a super admin
  frontends/election-manager/src/app.test.tsx
  frontends/election-manager/src/components/election_manager.tsx
  frontends/election-manager/src/components/smartcard_modal/card_details_view.tsx
  frontends/election-manager/src/components/smartcard_modal/index.ts
  frontends/election-manager/src/components/smartcard_modal/program_election_card_view.tsx
  frontends/election-manager/src/components/smartcard_modal/program_super_admin_card_view.tsx
  frontends/election-manager/src/components/smartcard_modal/smartcard_modal.tsx
  frontends/election-manager/src/config/types.ts
  frontends/election-manager/src/screens/smartcards_screen.tsx
  libs/test-utils/src/smartcard_auth/auth.ts
  libs/test-utils/src/smartcard_auth/dipped.ts
  libs/types/src/smartcard_auth/auth.ts
  libs/types/src/smartcard_auth/dipped_smartcard_auth.ts
  libs/ui/src/hooks/smartcard_auth/auth_helpers.ts
  libs/ui/src/hooks/smartcard_auth/use_dipped_smartcard_auth.ts
  libs/ui/src/remove_card_screen.tsx
Labels: user_facing_change

#2126 chore(precinct-scanner): Make ballots scanned text bigger
  frontends/precinct-scanner/src/components/scanned_ballot_count.tsx
  frontends/precinct-scanner/src/screens/admin_screen.tsx
  frontends/precinct-scanner/src/screens/insert_ballot_screen.tsx
  frontends/precinct-scanner/src/screens/poll_worker_screen.tsx
  frontends/precinct-scanner/src/screens/scan_success_screen.tsx
Labels: user_facing_change

#2138 Add write-ins to test decks
  frontends/election-manager/index.html
  frontends/election-manager/public/fonts/EduTASBeginner-VariableFont_wght.ttf
  frontends/election-manager/public/fonts/edu-tas-beginner.css
  frontends/election-manager/src/__snapshots__/app.test.tsx.snap
  frontends/election-manager/src/app.test.tsx
  frontends/election-manager/src/components/full_test_deck_tally_report_button.tsx
  frontends/election-manager/src/components/hand_marked_paper_ballot.tsx
  frontends/election-manager/src/screens/print_test_deck_screen.test.tsx
  frontends/election-manager/src/screens/print_test_deck_screen.tsx
  frontends/election-manager/src/utils/election.test.ts
  frontends/election-manager/src/utils/election.ts
  libs/types/src/election.ts
Labels: user_facing_change

#2139 feat(bmd): Prompt pollworker to open/close polls on VxScan if no tally report on card
  frontends/bmd/src/app_cardless_voting.test.tsx
  frontends/bmd/src/app_end_to_end.test.tsx
  frontends/bmd/src/app_mark_only.test.tsx
  frontends/bmd/src/app_print_only.test.tsx
  frontends/bmd/src/pages/poll_worker_screen.test.tsx
  frontends/bmd/src/pages/poll_worker_screen.tsx
Labels: user_facing_change

#2147 Fix BMD Ballot in VxAdmin
  frontends/bmd/src/App.css
  frontends/bmd/src/pages/__snapshots__/print_page.test.tsx.snap
  frontends/election-manager/src/__snapshots__/app.test.tsx.snap
  frontends/election-manager/src/app.test.tsx
  frontends/election-manager/src/screens/print_test_deck_screen.test.tsx
  frontends/election-manager/src/screens/print_test_deck_screen.tsx
  frontends/election-manager/test/util/load_ballot_seal_images.ts
  libs/ui/src/__snapshots__/bmd_paper_ballot.test.tsx.snap
  libs/ui/src/bmd_paper_ballot.test.tsx
  libs/ui/src/bmd_paper_ballot.tsx
Labels: bug

#2162 feat(bmd): open/close polls when printing report
  frontends/bmd/src/app_end_to_end.test.tsx
  frontends/bmd/src/pages/poll_worker_screen.test.tsx
  frontends/bmd/src/pages/poll_worker_screen.tsx
Labels: user_facing_change

#2159 Complete new smartcard programming UIs
  frontends/election-manager/src/app.test.tsx
  frontends/election-manager/src/components/smartcard_modal/card_details_view.tsx
  frontends/election-manager/src/components/smartcard_modal/pins.test.ts
  frontends/election-manager/src/components/smartcard_modal/pins.ts
  frontends/election-manager/src/components/smartcard_modal/program_election_card_view.tsx
  frontends/election-manager/src/components/smartcard_modal/program_super_admin_card_view.tsx
  frontends/election-manager/src/components/smartcard_modal/smartcard_modal.test.tsx
  frontends/election-manager/src/components/smartcard_modal/smartcard_modal.tsx
  frontends/election-manager/src/components/smartcard_modal/status_message.tsx
  frontends/election-manager/src/components/smartcard_modal/unprogram_card_confirmation_modal.tsx
  frontends/election-manager/src/components/smartcard_modal/user_roles.ts
  frontends/election-manager/test/util/create_memory_storage_with.ts
Labels: user_facing_change

#2164 fix(bmd): remove voter card copy
  frontends/bmd/src/app_card_unhappy_paths.test.tsx
  frontends/bmd/src/app_cardless_voting.test.tsx
  frontends/bmd/src/app_end_to_end.test.tsx
  frontends/bmd/src/app_mark_only.test.tsx
  frontends/bmd/src/app_mark_voter_card_invalid.test.tsx
  frontends/bmd/src/app_quit_on_idle.test.tsx
  frontends/bmd/src/app_setup_errors.test.tsx
  frontends/bmd/src/pages/insert_card_screen.tsx
Labels: user_facing_change

#2166 feat(bsd): reset batch count on mode toggle
  services/scan/src/store.test.ts
  services/scan/src/store.ts
Labels: user_facing_change

#2180 test(bmd): upgrade cypress
  frontends/bmd/README.md
  frontends/bmd/cypress.config.ts
  frontends/bmd/cypress.json
  frontends/bmd/cypress/plugins/index.js
  frontends/bmd/cypress/support/e2e.js
  frontends/bmd/cypress/support/index.js
  frontends/bmd/cypress/tests/font_settings.cy.ts
  frontends/bmd/cypress/tests/scroll_buttons.cy.ts
  frontends/bmd/cypress/tests/scroll_to_con.cy.ts
  frontends/bmd/cypress/tsconfig.json
  frontends/bmd/package.json
  pnpm-lock.yaml
Labels: tech-improvement

#2201 Add PINs to super admin smartcards
  frontends/bmd/src/app_end_to_end.test.tsx
  frontends/bsd/src/app.test.tsx
  frontends/election-manager/jest.config.js
  frontends/election-manager/src/app.test.tsx
  frontends/election-manager/src/components/smartcard_modal/card_details_view.tsx
  frontends/election-manager/src/components/smartcard_modal/program_election_card_view.tsx
  frontends/election-manager/src/components/smartcard_modal/program_super_admin_card_view.tsx
  frontends/election-manager/src/components/smartcard_modal/smartcard_modal.test.tsx
  frontends/election-manager/src/components/smartcard_modal/status_message.tsx
  frontends/election-manager/src/components/smartcard_modal/user_roles.ts
  frontends/precinct-scanner/src/app.test.tsx
  libs/test-utils/jest.config.js
  libs/test-utils/src/smartcard_auth/auth.ts
  libs/test-utils/src/smartcard_auth/inserted.ts
  libs/test-utils/src/smartcards.ts
  libs/types/src/smartcard_auth/auth.ts
  libs/types/src/smartcard_auth/dipped_smartcard_auth.ts
  libs/types/src/smartcard_auth/inserted_smartcard_auth.ts
  libs/ui/src/hooks/smartcard_auth/auth_helpers.test.ts
  libs/ui/src/hooks/smartcard_auth/auth_helpers.ts
  libs/ui/src/hooks/smartcard_auth/use_dipped_smartcard_auth.test.ts
  libs/ui/src/hooks/smartcard_auth/use_dipped_smartcard_auth.ts
  libs/ui/src/hooks/smartcard_auth/use_inserted_smartcard_auth.test.ts
  libs/ui/src/hooks/smartcard_auth/use_inserted_smartcard_auth.ts
  services/smartcards/mockCardReader.py
  services/smartcards/writeAdminCard.py
  services/smartcards/writePollWorkerCard.py
  services/smartcards/writeSuperAdminCard.py
  services/smartcards/writeToCard.py
  services/smartcards/writeVoterCard.py
Labels: user_facing_change

#2129 Precinct scanner state machine
  frontends/precinct-scanner/jest.config.js
  frontends/precinct-scanner/src/api/scan.test.ts
  frontends/precinct-scanner/src/api/scan.ts
  frontends/precinct-scanner/src/app.test.tsx
  frontends/precinct-scanner/src/app_root.tsx
  frontends/precinct-scanner/src/app_tally_report_paths.test.tsx
  frontends/precinct-scanner/src/app_unhappy_paths.test.tsx
  frontends/precinct-scanner/src/components/calibrate_scanner_modal.test.tsx
  frontends/precinct-scanner/src/components/calibrate_scanner_modal.tsx
  frontends/precinct-scanner/src/config/globals.ts
  frontends/precinct-scanner/src/config/types.ts
  frontends/precinct-scanner/src/hooks/use_precinct_scanner.test.ts
  frontends/precinct-scanner/src/hooks/use_precinct_scanner.ts
  frontends/precinct-scanner/src/hooks/use_precinct_scanner_status.test.ts
  frontends/precinct-scanner/src/hooks/use_precinct_scanner_status.ts
  frontends/precinct-scanner/src/preview_app.tsx
  frontends/precinct-scanner/src/screens/admin_screen.test.tsx
  frontends/precinct-scanner/src/screens/admin_screen.tsx
  frontends/precinct-scanner/src/screens/scan_busy_screen.tsx
  frontends/precinct-scanner/src/screens/scan_error_screen.test.tsx
  frontends/precinct-scanner/src/screens/scan_error_screen.tsx
  frontends/precinct-scanner/src/screens/scan_jam_screen.tsx
  frontends/precinct-scanner/src/screens/scan_returned_ballot_screen.tsx
  frontends/precinct-scanner/src/screens/scan_success_screen.tsx
  frontends/precinct-scanner/src/screens/scan_warning_screen.test.tsx
  frontends/precinct-scanner/src/screens/scan_warning_screen.tsx
  frontends/precinct-scanner/src/screens/setup_scanner_screen.tsx
  frontends/precinct-scanner/src/utils/build_scanning_result.test.ts
  frontends/precinct-scanner/src/utils/build_scanning_result.ts
  libs/api/src/services/scan/index.ts
  libs/ballot-interpreter-nh/src/interpret/index.ts
  libs/plustek-sdk/src/paper_status.ts
  libs/plustek-sdk/src/scanner.test.ts
  pnpm-lock.yaml
  services/scan/jest.config.js
  services/scan/package.json
  services/scan/src/central_scanner_app.test.ts
  services/scan/src/central_scanner_app.ts
  services/scan/src/end_to_end.test.ts
  services/scan/src/end_to_end_hmpb.test.ts
  services/scan/src/loop_scanner.ts
  services/scan/src/precinct_scanner_app.ts
  services/scan/src/precinct_scanner_state_machine.ts
  services/scan/src/scanners/fujitsu.ts
  services/scan/src/server.ts
  services/scan/src/simple_interpreter.ts
  services/scan/src/store.test.ts
  services/scan/src/types.ts
Labels: user_facing_change

#2224 Update admin (i.e. election manager) card user validation logic
  frontends/bmd/src/app_root.tsx
  frontends/bsd/src/app.test.tsx
  frontends/bsd/src/app_root.tsx
  frontends/election-manager/src/app.test.tsx
  frontends/election-manager/src/app_root.tsx
  frontends/election-manager/src/components/election_manager.tsx
  frontends/election-manager/src/components/navigation_screen.tsx
  frontends/election-manager/src/components/smartcard_modal/smartcard_modal.test.tsx
  frontends/election-manager/src/config/features.ts
  frontends/election-manager/src/env.d.ts
  frontends/election-manager/src/screens/unconfigured_screen.tsx
  frontends/precinct-scanner/src/app.test.tsx
  libs/types/src/smartcard_auth/dipped_smartcard_auth.ts
  libs/types/src/smartcard_auth/inserted_smartcard_auth.ts
  libs/ui/src/config/features.ts
  libs/ui/src/env.d.ts
  libs/ui/src/hooks/smartcard_auth/auth_helpers.test.ts
  libs/ui/src/hooks/smartcard_auth/use_dipped_smartcard_auth.test.ts
  libs/ui/src/hooks/smartcard_auth/use_dipped_smartcard_auth.ts
  libs/ui/src/hooks/smartcard_auth/use_inserted_smartcard_auth.test.ts
  libs/ui/src/hooks/smartcard_auth/use_inserted_smartcard_auth.ts
  libs/ui/src/index.ts
  libs/ui/src/invalid_card_screen.test.tsx
  libs/ui/src/invalid_card_screen.tsx
Labels: user_facing_change

#2221 Save All Ballot PDFs
  frontends/election-manager/src/__snapshots__/app.test.tsx.snap
  frontends/election-manager/src/components/ballot_copies_input.tsx
  frontends/election-manager/src/components/ballot_mode_toggle.tsx
  frontends/election-manager/src/components/ballot_type_toggle.tsx
  frontends/election-manager/src/components/export_ballot_pdfs_button.test.tsx
  frontends/election-manager/src/components/export_ballot_pdfs_button.tsx
  frontends/election-manager/src/components/export_election_ballot_package_modal_button.tsx
  frontends/election-manager/src/components/hand_marked_paper_ballot.tsx
  frontends/election-manager/src/components/save_file_to_usb.test.tsx
  frontends/election-manager/src/components/save_file_to_usb.tsx
  frontends/election-manager/src/config/types.ts
  frontends/election-manager/src/screens/ballot_list_screen.tsx
  frontends/election-manager/src/screens/ballot_screen.tsx
  frontends/election-manager/src/screens/print_test_deck_screen.tsx
  frontends/election-manager/src/utils/election.test.ts
  frontends/election-manager/src/utils/election.ts
  frontends/election-manager/src/utils/generate_pdf_export_metadata_csv.test.ts
  frontends/election-manager/src/utils/generate_pdf_export_metadata_csv.ts
  frontends/election-manager/src/utils/get_all_ballot_configs.ts
  libs/utils/src/filenames.ts
Labels: user_facing_change

#2236 Update non-VxAdmin system administrator screens
  frontends/bmd/src/app_end_to_end.test.tsx
  frontends/bmd/src/app_root.tsx
  frontends/bmd/src/pages/admin_screen.tsx
  frontends/bmd/src/pages/superadmin_screen.test.tsx
  frontends/bmd/src/pages/superadmin_screen.tsx
  frontends/bsd/src/app.test.tsx
  frontends/bsd/src/app_root.tsx
  frontends/precinct-scanner/jest.config.js
  frontends/precinct-scanner/src/app.test.tsx
  frontends/precinct-scanner/src/app_root.tsx
  libs/ui/src/config/features.ts
  libs/ui/src/index.ts
  libs/ui/src/reboot_to_bios_button.test.tsx
  libs/ui/src/reboot_to_bios_button.tsx
  libs/ui/src/system_administrator_screen_contents.test.tsx
  libs/ui/src/system_administrator_screen_contents.tsx
  libs/ui/src/unconfigure_machine_button.test.tsx
  libs/ui/src/unconfigure_machine_button.tsx
  vxsuite.code-workspace
Labels: user_facing_change
